import React from 'react';
import './ProjectStats.css';

interface ProjectStatsProps {
  stats: {
    totalConversations: number;
    totalProjects: number;
    codeFilesGenerated: number;
    voiceCommandsToday: number;
  };
}

const ProjectStats: React.FC<ProjectStatsProps> = ({ stats }) => {
  const statItems = [
    {
      id: 'conversations',
      label: 'Total Conversations',
      value: stats.totalConversations,
      icon: 'bi-chat-dots',
      color: '#007acc',
      description: 'Chat sessions with AI',
    },
    {
      id: 'projects',
      label: 'Projects',
      value: stats.totalProjects,
      icon: 'bi-folder',
      color: '#28a745',
      description: 'Active coding projects',
    },
    {
      id: 'files',
      label: 'Code Files Generated',
      value: stats.codeFilesGenerated,
      icon: 'bi-file-code',
      color: '#6f42c1',
      description: 'Generated by AI',
    },
    {
      id: 'voice-today',
      label: "Today's Voice Commands",
      value: stats.voiceCommandsToday,
      icon: 'bi-mic',
      color: '#fd7e14',
      description: 'Voice interactions today',
    },
  ];

  const formatValue = (value: number) => {
    if (value >= 1000000) {
      return (value / 1000000).toFixed(1) + 'M';
    }
    if (value >= 1000) {
      return (value / 1000).toFixed(1) + 'K';
    }
    return value.toString();
  };

  return (
    <div className="project-stats">
      <div className="stats-header">
        <h3>Overview</h3>
        <p>Your development activity summary</p>
      </div>
      
      <div className="stats-grid">
        {statItems.map((stat) => (
          <div
            key={stat.id}
            className="stat-card"
            style={{ '--stat-color': stat.color } as React.CSSProperties}
          >
            <div className="stat-icon">
              <i className={`bi ${stat.icon}`}></i>
            </div>
            
            <div className="stat-content">
              <div className="stat-value">{formatValue(stat.value)}</div>
              <div className="stat-label">{stat.label}</div>
              <div className="stat-description">{stat.description}</div>
            </div>
            
            <div className="stat-trend">
              {stat.value > 0 && (
                <div className="trend-indicator positive">
                  <i className="bi bi-arrow-up"></i>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
      
      {/* Additional insights */}
      <div className="stats-insights">
        <div className="insight-item">
          <i className="bi bi-lightbulb"></i>
          <span>
            {stats.voiceCommandsToday > 5 
              ? "Great job! You're actively using voice commands today."
              : stats.totalConversations > 0
              ? "Try using voice commands for faster development."
              : "Start your first voice conversation to see AI in action!"
            }
          </span>
        </div>
        
        {stats.totalProjects > 0 && stats.codeFilesGenerated === 0 && (
          <div className="insight-item">
            <i className="bi bi-code-slash"></i>
            <span>Generate your first code files using voice commands or chat.</span>
          </div>
        )}
        
        {stats.codeFilesGenerated > 10 && (
          <div className="insight-item">
            <i className="bi bi-trophy"></i>
            <span>Impressive! You've generated {stats.codeFilesGenerated} code files.</span>
          </div>
        )}
      </div>
    </div>
  );
};

export default ProjectStats;